version: '3.9'

services:
  dozero:
    build: .
    ports:
      - "5001:5001"
      - "8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_GENERATE_ASPNET_CERTIFICATE: "true"
      ASPNETCORE_URLS: https://+:5001;http://+:5000