version: '3.9'

services:
  app:
    build: .
    container_name: app_dotnet2
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./:/App
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_GENERATE_ASPNET_CERTIFICATE: "true"
      ASPNETCORE_URLS: https://+:5001;http://+:5000
